language: python

sudo: true

branches:
  only:
    - master

env:
  # - PYTHON_VERSION=2.7
  # - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

install:
  - sudo apt-get update
  - sudo apt-get install -y libfreetype6-dev libfontconfig1-dev
  - if [ "$PYTHON_VERSION" == "2.7" ]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - . $HOME/miniconda/etc/profile.d/conda.sh;
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes --quiet conda
  - conda info -a
  - conda activate
  - conda install python=$PYTHON_VERSION
  - conda install -c defaults -c conda-forge --file requirements.txt
  - conda install -c defaults -c conda-forge --file requirements_dev.txt
  - pip install python-coveralls
  - npm install
  - pip install .

script:
  - npm run test

after_success:
  - coveralls
