language: python

sudo: true

branches:
  only:
    - master

env:
  global:
    - NAME=test_jupyter_conda
  matrix:
    - PYTHON_VERSION=3.6 DEPS="typing"
    - PYTHON_VERSION=3.7 DEPS=""

before_install:
  - deactivate # Deactivate the default Travis virtualenv
  - sudo apt-get update
  - sudo apt-get install -y libfreetype6-dev libfontconfig1-dev
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - . $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda activate

install:
  - conda create -n $NAME  -c conda-forge -c defaults python=$PYTHON_VERSION $DEPS
  - conda activate $NAME
  - conda info -a
  - conda install -n $NAME -c conda-forge -c defaults --file requirements_dev.txt
  - pip install python-coveralls
  - npm install
  # Install the server and notebook extensions
  - pip install .
  # Install the jupyterlab extension
  - cd labextension
  - conda install -n $NAME -c conda-forge -c defaults jupyterlab
  - jlpm install
  - jupyter labextension install jupyterlab_toastify --no-build
  - jupyter labextension install .
  - cd ..

script:
  - npm run test

after_success:
  - coveralls
