language: python

sudo: true

branches:
  only:
    - master

env:
  - PYTHON_VERSION=3.7

install:
  - sudo apt-get update
  - sudo apt-get install -y libfreetype6-dev libfontconfig1-dev
  - if [ "$PYTHON_VERSION" == "2.7" ]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - . $HOME/miniconda/etc/profile.d/conda.sh;
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes --quiet conda
  - conda install -n root conda conda-env anaconda-client
  - conda info -a
  - conda create -n jupyter_conda python=$PYTHON_VERSION
  - conda install -n jupyter_conda -c conda-forge --file requirements.txt
  - conda install -n jupyter_conda -c conda-forge --file requirements_dev.txt
  - conda activate jupyter_conda
  - pip install python-coveralls
  - npm install

script:
  - pip install -e .
  - jupyter nbextension install jupyter_conda --py --sys-prefix --symlink
  - jupyter nbextension enable jupyter_conda --py --sys-prefix
  - jupyter serverextension enable jupyter_conda --py --sys-prefix
  - npm run test

after_success:
  - coveralls
