channels:
  - conda-forge
dependencies:
  - python >=3.6,<3.9
  - jupyterlab =2
  - jupyter-server-proxy
  - mamba
  - nb_conda_kernels >=2.2.3
  - nodejs >=11
  - yarn
  - notebook >=4.3.1
  - packaging
